import React from "react";
import {
  MonitorSmartphone,
  Building2,
  Briefcase,
  Newspaper,
  CalendarCheck,
  Users,
  MessageCircle,
  Smartphone,
  Utensils,
  BookOpen,
  Hotel,
  ShoppingBag,
  ShoppingCart,
  HeartPulse,
  GraduationCap,
  BarChart3,
  Truck,
} from "lucide-react";

export const additionalServices = [
  { label: "Landing Pages", icon: <MonitorSmartphone size={15} /> },
  { label: "Business Websites", icon: <Building2 size={15} /> },
  { label: "Portfolio Websites", icon: <Briefcase size={15} /> },
  { label: "Blog Platforms", icon: <Newspaper size={15} /> },
  { label: "Booking & Appointment Systems", icon: <CalendarCheck size={15} /> },
  { label: "Membership & Subscription Sites", icon: <Users size={15} /> },
  { label: "Real-time Chat Apps", icon: <MessageCircle size={15} /> },
  { label: "Social Media Platforms", icon: <Smartphone size={15} /> },
  { label: "Food Delivery Apps", icon: <Utensils size={15} /> },
  { label: "Job Portals", icon: <Briefcase size={15} /> },
  { label: "E-learning Platforms", icon: <BookOpen size={15} /> },
  { label: "Event Management Systems", icon: <CalendarCheck size={15} /> },
  { label: "Travel & Hotel Booking", icon: <Hotel size={15} /> },
  { label: "Marketplace Platforms", icon: <ShoppingBag size={15} /> },
  { label: "Multi-vendor Shops", icon: <ShoppingCart size={15} /> },
  { label: "Healthcare Management", icon: <HeartPulse size={15} /> },
  { label: "School & College Management", icon: <GraduationCap size={15} /> },
  { label: "Accounting & Finance Tools", icon: <BarChart3 size={15} /> },
  { label: "Analytics Dashboards", icon: <BarChart3 size={15} /> },
  { label: "Courier & Delivery Tracking", icon: <Truck size={15} /> },
  { label: "Real Estate Platforms", icon: <Building2 size={15} /> },
  { label: "News & Magazine Sites", icon: <Newspaper size={15} /> },
];
