import React from "react";
import {
  ShoppingCart,
  Globe,
  Code2,
  Server,
  Cloud,
  Link,
} from "lucide-react";

export const servicesPart1 = [
  {
    id: 1,
    title: "E-Commerce Development",
    description: "Secure, scalable online stores with payment gateways, inventory management, and powerful admin dashboards.",
    icon: <ShoppingCart size={28} />,
    features: [
      "Custom Shopping Cart",
      "Payment Gateway (Stripe, SSLCommerz, bKash, Nagad)",
      "Product Management System",
      "Order Tracking",
      "Inventory Management",
      "Customer Accounts",
      "Admin Dashboard",
      "Analytics & Reports",
      "Discount & Coupon System",
      "Multi-vendor Marketplace",
    ],
    tech: ["Next.js", "Node.js", "MongoDB", "Stripe", "SSLCommerz", "Redis"],
    color: "from-emerald-500/15 to-teal-500/10",
    borderColor: "border-emerald-500/30",
    iconColor: "text-emerald-500",
  },
  {
    id: 2,
    title: "Custom Website Development",
    description: "Tailored websites built from scratch to match your unique business requirements, brand identity, and goals.",
    icon: <Globe size={28} />,
    features: [
      "Responsive Design (Mobile-first)",
      "SEO Optimization",
      "Performance Tuning",
      "CMS Integration",
      "Custom Animations",
      "Progressive Web App (PWA)",
      "Multi-language Support",
      "Accessibility Compliance",
      "Domain & Hosting Setup",
      "Google Analytics Integration",
    ],
    tech: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "Next.js"],
    color: "from-blue-500/15 to-indigo-500/10",
    borderColor: "border-blue-500/30",
    iconColor: "text-blue-500",
  },
  {
    id: 3,
    title: "Custom Software Development",
    description: "Business-specific software solutions — from internal tools to complex enterprise systems built to your workflow.",
    icon: <Code2 size={28} />,
    features: [
      "ERP / CRM Systems",
      "HR & Payroll Management",
      "POS (Point of Sale) Systems",
      "School / Hospital Management",
      "Inventory Software",
      "Accounting Software",
      "Workflow Automation",
      "Custom Reporting Tools",
      "Role-based Access Control",
      "Multi-branch Support",
    ],
    tech: ["React", "Node.js", "PostgreSQL", "MongoDB", "Docker", "AWS"],
    color: "from-violet-500/15 to-purple-500/10",
    borderColor: "border-violet-500/30",
    iconColor: "text-violet-500",
  },
  {
    id: 4,
    title: "Full-Stack Web Applications",
    description: "End-to-end web apps with robust backend APIs, real-time features, databases, and modern frontends.",
    icon: <Server size={28} />,
    features: [
      "RESTful API Development",
      "Database Design & Optimization",
      "JWT Authentication & OAuth",
      "Real-time Features (Socket.io)",
      "Cloud Deployment (AWS, Vercel)",
      "Microservices Architecture",
      "Third-party Integrations",
      "Scalable Infrastructure",
      "Email & SMS Notifications",
      "File Upload & Media Management",
    ],
    tech: ["MERN Stack", "PostgreSQL", "GraphQL", "Docker", "AWS", "Redis"],
    color: "from-foreground/5 to-transparent",
    borderColor: "border-border",
    iconColor: "text-foreground",
  },
  {
    id: 5,
    title: "SaaS Application Development",
    description: "Subscription-based software products with multi-tenancy, billing, and scalable cloud infrastructure.",
    icon: <Cloud size={28} />,
    features: [
      "Multi-tenant Architecture",
      "Subscription & Billing (Stripe)",
      "User Onboarding Flow",
      "Usage-based Pricing",
      "Team & Workspace Management",
      "Analytics Dashboard",
      "Webhook & API Access",
      "White-label Support",
      "Auto-scaling Infrastructure",
      "Admin Super Panel",
    ],
    tech: ["Next.js", "Node.js", "PostgreSQL", "Stripe", "AWS", "Redis"],
    color: "from-cyan-500/15 to-sky-500/10",
    borderColor: "border-cyan-500/30",
    iconColor: "text-cyan-500",
  },
  {
    id: 6,
    title: "API Development & Integration",
    description: "Custom API development and seamless third-party service integrations for enhanced functionality.",
    icon: <Link size={28} />,
    features: [
      "REST API Design",
      "GraphQL APIs",
      "Payment Gateway Integration",
      "Social Media APIs",
      "CRM Integration",
      "Email & SMS Service (Twilio, SendGrid)",
      "Webhook Implementation",
      "API Documentation (Swagger)",
      "Rate Limiting & Security",
      "Third-party OAuth (Google, Facebook)",
    ],
    tech: ["Node.js", "Express", "GraphQL", "OAuth", "JWT", "Swagger"],
    color: "from-yellow-500/15 to-amber-500/10",
    borderColor: "border-yellow-500/30",
    iconColor: "text-yellow-500",
  },
];
