import React from "react";
import {
  Smartphone,
  LayoutDashboard,
  BrainCircuit,
  Palette,
  Building2,
  ShieldCheck,
} from "lucide-react";

export const servicesPart2 = [
  {
    id: 7,
    title: "Mobile App Development",
    description: "Cross-platform mobile apps for iOS and Android using React Native with native-like performance.",
    icon: <Smartphone size={28} />,
    features: [
      "React Native Development",
      "iOS & Android Support",
      "Push Notifications",
      "Offline Mode",
      "App Store Deployment",
      "Google Play Deployment",
      "Camera & GPS Integration",
      "Payment Integration",
      "Real-time Updates",
      "Native UI Components",
    ],
    tech: ["React Native", "TypeScript", "Node.js", "Firebase", "Expo", "MongoDB"],
    color: "from-rose-500/15 to-pink-500/10",
    borderColor: "border-rose-500/30",
    iconColor: "text-rose-500",
  },
  {
    id: 8,
    title: "Admin Dashboard & CMS",
    description: "Powerful admin panels, content management systems, and back-office tools to manage your business easily.",
    icon: <LayoutDashboard size={28} />,
    features: [
      "Custom Admin Panels",
      "Role & Permission Management",
      "Data Tables & Filters",
      "Charts & Analytics",
      "CMS (Content Management)",
      "Blog / News Management",
      "Media Library",
      "User Management",
      "Audit Logs",
      "Export to PDF / Excel",
    ],
    tech: ["React", "Tailwind CSS", "Node.js", "MongoDB", "Chart.js", "shadcn/ui"],
    color: "from-foreground/5 to-transparent",
    borderColor: "border-border",
    iconColor: "text-foreground",
  },
  {
    id: 9,
    title: "AI & Smart Features Integration",
    description: "Add intelligent features to your product — chatbots, AI content generation, smart search, and automation.",
    icon: <BrainCircuit size={28} />,
    features: [
      "AI Chatbot Integration (OpenAI)",
      "Smart Search (Semantic)",
      "AI Content Generation",
      "Image Recognition",
      "Recommendation Engine",
      "Sentiment Analysis",
      "Data Prediction Models",
      "Voice Assistant Integration",
      "Auto-tagging & Classification",
      "Mongoose AI Queries",
    ],
    tech: ["OpenAI API", "LangChain", "Node.js", "MongoDB", "Python", "Vercel AI SDK"],
    color: "from-fuchsia-500/15 to-violet-500/10",
    borderColor: "border-fuchsia-500/30",
    iconColor: "text-fuchsia-500",
  },
  {
    id: 10,
    title: "UI/UX Design Implementation",
    description: "Converting Figma/XD designs into pixel-perfect, responsive, and interactive web interfaces.",
    icon: <Palette size={28} />,
    features: [
      "Figma / XD to Code",
      "Responsive Layouts",
      "Custom Animations (GSAP, Framer)",
      "Component Libraries",
      "Cross-browser Testing",
      "Mobile-first Design",
      "Interactive Prototypes",
      "Design Systems",
      "Dark / Light Mode",
      "Micro-interactions",
    ],
    tech: ["React", "Tailwind", "Framer Motion", "GSAP", "Storybook"],
    color: "from-pink-500/15 to-rose-500/10",
    borderColor: "border-pink-500/30",
    iconColor: "text-pink-500",
  },
  {
    id: 11,
    title: "Company IT Solutions",
    description: "End-to-end digital transformation for companies — from internal tools to client-facing products and team portals.",
    icon: <Building2 size={28} />,
    features: [
      "Company Website & Portal",
      "Employee Management System",
      "Internal Communication Tools",
      "Project & Task Management",
      "Client Management (CRM)",
      "Invoice & Billing System",
      "Document Management",
      "HR & Leave Management",
      "Custom Reporting & KPIs",
      "Multi-department Access Control",
    ],
    tech: ["Next.js", "Node.js", "PostgreSQL", "MySQL", "Docker", "AWS"],
    color: "from-slate-500/15 to-zinc-500/10",
    borderColor: "border-slate-500/30",
    iconColor: "text-slate-400",
  },
  {
    id: 12,
    title: "Website Maintenance & Optimization",
    description: "Keep your website secure, fast, and up-to-date with ongoing maintenance and performance tuning.",
    icon: <ShieldCheck size={28} />,
    features: [
      "Security Updates & Patches",
      "Performance Monitoring",
      "Bug Fixes",
      "Content Updates",
      "Backup Management",
      "SSL Certificate Setup",
      "Uptime Monitoring",
      "Core Web Vitals Optimization",
      "Speed Optimization",
      "Technical Support",
    ],
    tech: ["DevOps", "CI/CD", "Monitoring", "Analytics", "Security"],
    color: "from-orange-500/15 to-red-500/10",
    borderColor: "border-orange-500/30",
    iconColor: "text-orange-500",
  },
];
